<%-- 
    Document   : about
    Created on : Aug 21, 2015, 2:20:31 PM
    Author     : eneye380
--%>


<%@include file="../header/header.jsp" %>

<!-- Page Content -->
<div class="container" >

    
    

    <!-- Title -->
    
    <!-- /.row -->
    <div class="container jumbotron">
        <div class="thumbnail">
            
            <p class="text-center"><em>The purpose of this evaluation is to find out the usefulness of different types of information and the role they play in online product purchase decision making. In particular we explore different levels of information granularity starting from general product star ratings, ranking, rating frequency to more specialized forms of product aspect sentiments extracted from reviews. 
A product?s star rating summaries the overall buyer?s opinion usually on a Likert scale from 1 to 5, products ranking shows the popularity of products, rating frequency is the distribution over the number of people who provided star ratings. Whilst an Aspect Sentiment Score is a negative or positive score assigned to a product?s feature (aspect). For example, if a user says ?the lens is good?, we can infer that a positive sentiment score can be associated with the aspect lens, on the other hand, if the user says ?the battery life is poor?; a negative sentiment is inferred about the aspect battery. A sentiment aggregation over such aspects provides a snapshot of opinions captured within product reviews. 
Recommender System Overview</em></p>

<p>The system presented to you is a recommender system with explanation interface which allows you to select a product from any category thereupon redirecting you to the product recommendation page that displays the product selected (the query product) along with a set of recommended products generated by the recommender system, also contained on this page are four (4) styles of explanations for product recommendations namely: 
<pre>
1.	Aspect Sentiment Graph (ASG) 
2.	Star Rating (SR) 
3.	Product Ranking (PR) 
4.	Ratings Frequency Distribution Graph (RFDG)
        </pre>
<p p class="text-center"><em>Clicking on the query product image from the product recommendation page takes you to the product detail page where product reviews and other information can be found relating to the product. Clicking on the compare button on the product recommendation page takes you to the product comparison page where a detailed product comparison can be viewed. 
    Currently four product category exist. </em></p>

            
            
        </div>
        
        
        
    </div>
    <!-- /.row -->

    <hr>

    <%@include file="../footer/footer.jsp" %>
